name: YUJINLIM
favicon: null
layout_spectrum: 0.68163
typography_spectrum: 0.9681140265893191
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.4226938923820853
  saturation: 0.5323254084214568
  rhythmicContrast: 0.1788737738970667
purpose: []
